export const DEFAULT_PANEL_BACKGROUND_COLOR = "#18181bCC";
export const DEFAULT_PANEL_CORNER_RADIUS = 8;
export const DEFAULT_PANEL_BORDER_COLOR = "#00000000";
export const DEFAULT_PANEL_BORDER_WIDTH = 1;
export const DEFAULT_ICON_COLOR = "#FFFFFF";
